[general]
serverName = seim-lab
pass4SymmKey = $7$NCOUAtBNSaye+CbMDEAAhxj1HbKrL3xOaMgVNRhjHFWB5XipFbFL8g==

[sslConfig]
sslPassword = $7$nLcShxiXZUz05YGIbGkWaN6gGIl/Cq1wLGImK172ZqkhYubsQKDNRA==

[lmpool:auto_generated_pool_download-trial]
description = auto_generated_pool_download-trial
peers = *
quota = MAX
stack_id = download-trial

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free

[diskUsage]
minFreeSpace = 1000
